In [1]:
"""
Optimización usando gradiente descendente - Regresión polinomial
-----------------------------------------------------------------------------------------

En este laboratio se estimarán los parámetros óptimos de un modelo de regresión 
polinomial de grado `n`.

"""


def pregunta_01():
    """
    Complete el código presentado a continuación.
    """
    # Importe pandas
    import pandas as pd

    # Importe PolynomialFeatures
    from sklearn.preprocessing import PolynomialFeatures

    # Cargue el dataset `data.csv`
    data = pd.read_csv('data.csv')    
    
    # Cree un objeto de tipo `PolynomialFeatures` con grado `2`
    poly = PolynomialFeatures(2)

    # Transforme la columna `x` del dataset `data` usando el objeto `poly`
    x_poly = poly.fit_transform(data[["x"]])

    # Retorne x y y
    return x_poly, data.y


def pregunta_02():

    # Importe numpy
    import numpy as np

    x_poly, y = pregunta_01()

    # Fije la tasa de aprendizaje en 0.0001 y el número de iteraciones en 1000
    learning_rate = 0.0001
    n_iterations = 1000

    # Defina el parámetro inicial `params` como un arreglo de tamaño 3 con ceros
    params = np.zeros(x_poly.shape[1])
    for _ in range(n_iterations):

        # Compute el pronóstico con los parámetros actuales
        y_pred = np.sum(np.multiply(x_poly, params), axis = 1)

        # Calcule el error (MSE)
        error = y_pred - y
        
        # Calcule el gradiente
        a_derivative = sum(x_poly[:, 2] * (error))
        b_derivative = sum(x_poly[:, 1] * (error))
        c_derivative = sum(x_poly[:, 0] * (error))
        
        gradient = np.array([c_derivative, b_derivative, a_derivative])
        
        # Actualice los parámetros
        params = params - learning_rate * gradient

    return params


In [2]:
# Importe numpy
import numpy as np

x_poly, y = pregunta_01()

# Fije la tasa de aprendizaje en 0.0001 y el número de iteraciones en 1000
learning_rate = 0.0001
n_iterations = 1000

# Defina el parámetro inicial `params` como un arreglo de tamaño 3 con ceros
params = np.zeros(x_poly.shape[1])

for _ in range(n_iterations):
    '''
    # Compute el pronóstico con los parámetros actuales
    y_pred = np.sum(np.multiply(x_poly, params), axis = 1)

    n = len(y)

    # Calcule el error (MSE)
    error = np.sum((y-y_pred)**2) / n

    # Calcule el gradiente
    a_derivative = -(2/n) * sum(x_poly[:, 2] * (y - y_pred))
    b_derivative = -(2/n) * sum(x_poly[:, 1] * (y - y_pred))
    c_derivative = -(2/n) * sum(x_poly[:, 0] * (y - y_pred))

    gradient = np.array([c_derivative, b_derivative, a_derivative])

    # Actualice los parámetros
    params = params - learning_rate * gradient
    '''
    
    # Compute el pronóstico con los parámetros actuales
    y_pred = np.sum(np.multiply(x_poly, params), axis = 1)

    # Calcule el error
    error = y_pred - y

    # Calcule el gradiente
    
    a_derivative = sum(x_poly[:, 2] * (error))
    b_derivative = sum(x_poly[:, 1] * (error))
    c_derivative = sum(x_poly[:, 0] * (error))

    gradient_2 = np.array([c_derivative, b_derivative, a_derivative])
    
    #gradient = np.dot(x_poly.T, error)

    # Actualice los parámetros
    params = params - learning_rate * gradient_2


In [3]:
params

array([ 0.6664678 , -2.99999557,  2.03178244])

In [4]:
"""
Calificación del laboratorio
-----------------------------------------------------------------------------------------
"""

import sys

import numpy as np

def test_01():
    """
    ---< Run command >-------------------------------------------------------------------
    Pregunta 01
    pip3 install scikit-learn pandas numpy
    python3 tests.py 01
    """

    x_poly, _ = pregunta_01()
    x_poly = x_poly.round(3)
    x_expected = np.array(
        [
            [1.0, -4.0, 16.0],
            [1.0, -3.579, 12.809],
            [1.0, -3.158, 9.972],
            [1.0, -2.737, 7.49],
            [1.0, -2.316, 5.363],
            [1.0, -1.895, 3.59],
            [1.0, -1.474, 2.172],
            [1.0, -1.053, 1.108],
            [1.0, -0.632, 0.399],
            [1.0, -0.21, 0.044],
            [1.0, 0.21, 0.044],
            [1.0, 0.632, 0.399],
            [1.0, 1.053, 1.108],
            [1.0, 1.474, 2.172],
            [1.0, 1.895, 3.59],
            [1.0, 2.316, 5.363],
            [1.0, 2.737, 7.49],
            [1.0, 3.158, 9.972],
            [1.0, 3.579, 12.809],
            [1.0, 4.0, 16.0],
        ]
    )

    for i in range(x_poly.shape[0]):
        for j in range(x_poly.shape[1]):
            assert x_poly[i, j] == x_expected[i, j]

In [5]:
def test_02():
    """
    ---< Run command >-------------------------------------------------------------------
    Pregunta 02
    pip3 install scikit-learn pandas numpy
    python3 tests.py 02
    """
    params = pregunta_02()
    expected = np.array([0.666, -3.0, 2.032])
    assert np.allclose(params, expected, atol=1e-3)

In [6]:
test_01()

In [7]:
test_02()

In [8]:
a = [[4, 1], [1, 0]]
b = [[1, 3], [0, 2]]
np.dot(a, b)

array([[ 4, 14],
       [ 1,  3]])

In [9]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
m.shape

(4, 3)

In [11]:
e = [1, 2, 3, 4]

In [12]:
x_poly.shape

(20, 3)

In [13]:
m[:, 2]

array([ 3,  6,  9, 12])

In [14]:
a_derivative = sum(m[:, 2] * e)
b_derivative = sum(m[:, 1] * e)
c_derivative = sum(m[:, 0] * e)

gradient_2 = np.array([c_derivative, b_derivative, a_derivative])